### ISSUE TITLE
 vzPlayer object have issue with firefox

### ISSUE THREAD

**Issue by arieffikhrie** [vzaar/vzaar-jquery#2]
Hi,
Object from flashtakt.client.js which is vzPlayer is not working on firefox.

Video that i use is playing from flash
it showing this error
`Error: Permission denied to access property "href"[Learn More]`

Any ways to fixed it?

Im using that to do custom pause button at my page

``` javascript
vzp = new vzPlayer(playerID);
$('#btn').on('click', function(){
   vzp.pause();
});
```

**Comment by revdan** [comment]
Hi there,

This sounds like an issue with the JavaScript API, rather than this jQuery plugin specifically. If that is the case, then please get in touch with our support team by visiting http://help.vzaar.com/ and clicking the 'contact us' button at the bottom. They'll be much better placed to help out with this.

All the best,
Dan

**Comment by arieffikhrie** [comment]
Hi,
thanks for replying,
i have found another approach that does not use flashtakt.client.js
based on this demo http://vzaar.com/demo/js-api/bookmarks/
